default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 15
  username: root
  password:
  host: <%= File.exist?('/opt/dev') ? 'super-great-pizza.railgun' : 'localhost' %>
  port: 3306
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  database: super-great-pizza_development

test:
  <<: *default
  database: super-great-pizza_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  variables:
    sql_mode: TRADITIONAL
