# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:helpers to regenerate.
module ApiHelper
  include Kernel
  include ActionView::Helpers
end

module ApplicationHelper
  include Kernel
  include ActionView::Helpers
end

module DiscountsHelper
  include Kernel
  include ActionView::Helpers
end

module ListHelper
  include Kernel
  include ActionView::Helpers
end

module ProductTypesHelper
  include Kernel
  include ActionView::Helpers
end